Session/6
tom1236908745/flutter-training-weather-app pull request #20
Opened 2024-05-20 08:33 UTC by tom1236908745

## 課題

close #ISSUE_NUMBER

## 対応箇所

- [ ] xxx

## 動作

| expected | actual |
|----------|--------|
| xxx      | xxx    |

2024-05-22 08:04 UTC, tom1236908745 commented on lib/constant/initial_string.dart
> +};
[ask]

今まで他の言語では、アプリ全体で使用する定数は「大文字のスネークケース」で命名していたのですが、
その様にした所、「lowerCamelCase style」にする様にと、エラーが出てしまうのですが、flutterではこちらが慣例的なのでしょうか？

2024-05-22 08:32 UTC, tom1236908745 commented
@blendthink 
すみません、PR作成において、不備があったので、一旦再度Draftに戻しました

2024-05-22 08:36 UTC, tom1236908745 commented
@blendthink 
お待たせしました。変更を加えましたので、
再度レビューの方、よろしくお願いします。

2024-05-24 09:27 UTC, blendthink reviewed
@tom1236908745 
いくつかコメントしましたのでご確認お願いします 🙏

2024-05-24 09:27 UTC, blendthink commented on lib/model/weather_info_model.dart
> +      date: json['date'] as String,
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg)
この辺りの変換処理が安全でないようで、 `Exception` ではなく `Error` が発生してしまう危険性が潜んでいます。次のように Dart 3 の Patterns 機能を利用すると、より安全に書くことができるためおすすめです。
https://dart.dev/language/patterns

```dart
factory WeatherInfoModel.fromJson(Map<String, dynamic> json) {
  return switch (json) {
    {
      'weather_condition': final String weatherCondition,
      'max_temperature': final int maxTemperature,
      'min_temperature': final int minTemperature,
      'date': final String date,
    } =>
      WeatherInfoModel(
        weatherCondition: WeatherCondition.from(weatherCondition),
        maxTemperature: maxTemperature,
        minTemperature: minTemperature,
        date: date,
      ),
    _ => throw const FormatException(),
  };
}
```

さらにより細かく例外処理を行いたいという場合は↓が参考になると思います。
https://github.com/Yamasaki-pan961/flutter-yumemi-training/pull/19/files

2024-05-28 07:45 UTC, tom1236908745 reviewed
ご指摘の対応をさせて頂きました。
お手隙で再レビューの方よろしくお願いします！

2024-05-28 07:45 UTC, tom1236908745 commented on lib/model/weather_info_model.dart
> +      date: json['date'] as String,
@blendthink 
[feat: レスポンスデータ内の各プロパティに対しての例外処理の追加](https://github.com/tom1236908745/flutter-training-weather-app/pull/20/commits/f77943bd7243c922e61772ada293dce5bfe75d1a)

で対応させていただきました！

2024-05-28 07:45 UTC, tom1236908745 commented on lib/main_page_layout.dart
> +    required String? temperature,
@blendthink 

[fix: ビューモデル層の温度に関する型を文字列から数値型に修正](https://github.com/tom1236908745/flutter-training-weather-app/pull/20/commits/2afb9ae188285cab70865409f024405a31808642)

上記コミットで対応させて頂きました！
(lintでこけていた事気づけておらず、そのままコミットしておりました。次から気をつけます🙇)

2024-05-28 07:45 UTC, tom1236908745 commented on lib/repository/fetch_yumemi_weather.dart
> +      jsonDecode(weatherResponse) as Map<String, dynamic>,
@blendthink 

[fix: モデル層の変数の型に関する処理をパターンマッチングを使ったswitch文に修正](https://github.com/tom1236908745/flutter-training-weather-app/pull/20/commits/7f86356785547e9530d36564bb728b161bdebeed)

上記コミットで対応させて頂きました！

2024-05-28 08:21 UTC, blendthink commented on lib/view_model/weather_info.dart
> +  final String minTemperature;
↓で修正を確認しました。
2afb9ae188285cab70865409f024405a31808642

2024-05-28 09:03 UTC, blendthink requested changes
@tom1236908745 
いくつかコメントしましたのでご確認お願いします 🙏

2024-05-28 09:03 UTC, blendthink commented on lib/model/weather_info_model.dart
> +    }
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)
丁寧に１つずつ例外処理を実装できておりステキです✨

2024-05-28 09:03 UTC, blendthink commented on lib/model/weather_info_model.dart
> +  final DateTime date;
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)
`DateTime` 型にして、より安全に開発進められるようになっていてステキです✨

2024-05-28 09:03 UTC, blendthink commented on lib/constant/weather_condition.dart
> +    String? exceptionMessage,
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
`WeatherCondition` とは関係ない例外メッセージをここで付与するのは、責務が増えてしまってあまりいい設計とは言えないため削除お願いします 🙏 
何か不明点などあれば Slack などで気軽にご質問いただければと思います！

2024-05-29 01:37 UTC, tom1236908745 commented on lib/model/weather_info_model.dart
> +    final noJsonResponseMessage = json.isEmpty ? 'レスポンスデータが存在しません。\n' : '';
[fix: 日本語のメッセージを英語に修正](https://github.com/tom1236908745/flutter-training-weather-app/pull/20/commits/c8a9d928a96480e43dd499bd97331705e6a0034c)

上記コミットで対応させて頂きました！

2024-05-29 01:39 UTC, tom1236908745 commented on lib/model/throw_format_exception.dart
[fix: 共通関数の定義場所を修正](https://github.com/tom1236908745/flutter-training-weather-app/pull/20/commits/073554f170e672e36b72b8bfc562dd4bd4b2e5e8)

上記コミットで対応させて頂きました！

2024-05-29 01:39 UTC, tom1236908745 commented on lib/model/weather_info_model.dart
> +    final noJsonResponseMessage = json.isEmpty ? 'レスポンスデータが存在しません。\n' : '';
[fix: レスポンスのjsonデータが空の場合の処理を修正](https://github.com/tom1236908745/flutter-training-weather-app/pull/20/commits/d23e856ef391740306279cbca5a23a99d0eed72a)

上記コミットで対応させて頂きました！

2024-05-29 01:39 UTC, tom1236908745 commented on lib/model/weather_info_model.dart
> +    // `weather_condition` 用の例外処理
[fix: 不要なコメントの削除](https://github.com/tom1236908745/flutter-training-weather-app/pull/20/commits/0be078025c052dc45a0ff097325f2cc52cab6fcc)

上記コミットで対応させて頂きました！

2024-05-29 01:40 UTC, tom1236908745 commented on lib/constant/weather_condition.dart
> +    String? exceptionMessage,
[fix: レスポンスのjsonデータが空の場合の処理を修正](https://github.com/tom1236908745/flutter-training-weather-app/pull/20/commits/d23e856ef391740306279cbca5a23a99d0eed72a)

上記コミットで対応させて頂きました！

2024-05-29 01:41 UTC, tom1236908745 commented on lib/components/dialog/error_message_dialog.dart
dialogコンポーネント用のディレクトリ名が大文字から始まっていた件について、
こちらの PR・コミット で対応させて頂きました！

2024-05-29 01:42 UTC, tom1236908745 commented
ご指摘の修正を行いましたので、
お手隙で再度レビューの方お願いします！🙇

2024-05-29 01:49 UTC, blendthink commented on lib/components/dialog/error_message_dialog.dart
ご対応ありがとうございます！

2024-05-29 02:14 UTC, blendthink reviewed
@tom1236908745 
少し追加でコメントさせていただきましたのでご確認お願いします 🙏

2024-05-29 02:14 UTC, blendthink commented on lib/constant/fetch_failure_set_phrase.dart.dart
> +const String fetchFailureSetPhrase = 'APIからのデータ取得に失敗しました。\n\n内容: ';
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg) 
`lib/utils/format_fetch_failure_message.dart` でプライベートで定義するように修正した方が適切そうです。

理由としては
- 現状 `lib/utils/format_fetch_failure_message.dart` でしか使っていない
- 命名的に `formatFetchFailureMessage()` の方をどちらかといえば使い回しそう
- 他の文言も同じように管理するとなったら、都度ファイルの新規作成やファイル名の変更などが発生してしまい、開発効率があまり良くなさそう

2024-05-29 02:14 UTC, blendthink commented on lib/model/weather_info_model.dart
> +// `Exception` にスローする共通関数u
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg) 
修正お願いします 🙏

2024-05-29 02:14 UTC, blendthink commented on lib/utils/format_fetch_failure_message.dart
> +String formatFetchFailureMessage<T>(T failureMessage) {
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg) 
`lib/repository/fetch_yumemi_weather.dart` の中でプライベートで定義したほうが適切そうです。

理由としては
- 現状 `lib/repository/fetch_yumemi_weather.dart` 以外で使われていない
- 今後も命名的に　`lib/repository/fetch_yumemi_weather.dart` 以外で使われなさそう

2024-05-29 07:54 UTC, tom1236908745 commented on lib/constant/fetch_failure_set_phrase.dart.dart
> +const String fetchFailureSetPhrase = 'APIからのデータ取得に失敗しました。\n\n内容: ';
[fix: エラー時の文言とファイル構成の修正](https://github.com/tom1236908745/flutter-training-weather-app/pull/20/commits/4cd4a07057a3584c2706902ee71b5d2305e8f1b5)

上記コミットで対応させて頂きました！

2024-05-29 07:55 UTC, tom1236908745 commented on lib/model/weather_info_model.dart
> +// `Exception` にスローする共通関数u
[refactor: コメント文のタイポを修正](https://github.com/tom1236908745/flutter-training-weather-app/pull/20/commits/95728fc7a03b90417762ca174d6e7a3beebd582f)

上記コミットで対応させて頂きました！

2024-05-29 07:55 UTC, tom1236908745 commented on lib/utils/format_fetch_failure_message.dart
> +String formatFetchFailureMessage<T>(T failureMessage) {
[fix: 共通関数の配置を移動](https://github.com/tom1236908745/flutter-training-weather-app/pull/20/commits/92ecaf89f47ec51a9d70a4714f663f47f119f168)

上記コミットで対応させて頂きました！

2024-05-29 07:55 UTC, tom1236908745 commented
ご丁寧にレビューして頂きありがとうございます。
対応を行いましたので、再度レビューお願いします！

2024-05-29 08:05 UTC, blendthink reviewed
@tom1236908745 
追加で２点コメントさせていただきましたのでご確認お願いします 🙏

2024-05-29 08:05 UTC, blendthink commented on lib/model/weather_info_model.dart
> +// `Exception` にスローする共通関数
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg) 
```suggestion
/// `Exception` にスローする共通関数
```

2024-05-29 08:05 UTC, blendthink commented on lib/model/weather_info_model.dart
> +// `Exception` にスローする共通関数
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg) 
今気づいたのですが、「 `FormatException` をスローする共通関数」が日本語的に正しい気がするのですがいかがでしょうか？

2024-05-30 02:21 UTC, blendthink approved these changes
![LGTM](https://image.lgtmoon.dev/249090)

2024-05-30 02:24 UTC, merged