Session/10
tom1236908745/flutter-training-weather-app pull request #24
Opened 2024-07-05 02:06 UTC by tom1236908745

## 課題

close #11 

## 対応箇所
- [x] 特定の条件で、天気予報画面に晴れの画像が表示されること
- [x] 特定の条件で、天気予報画面に曇りの画像が表示されること
- [x] 特定の条件で、天気予報画面に雨の画像が表示されること
- [x] 特定の条件で、天気予報画面に最高気温が表示されること
- [x] 特定の条件で、天気予報画面に最低気温が表示されること
- [x] 特定の条件で、天気予報画面にダイアログが表示され、特定のメッセージが表示されること

2024-07-05 02:07 UTC, tom1236908745 commented on lib/view_model/weather_info_notifier.dart
> +        FailureMessage('Request Failed!\nUnable to process your '
不要な空白が有りましたので、この際に削除しておきました。

2024-07-10 01:44 UTC, blendthink requested changes
@tom1236908745 
前回の MTG のときにレビューしきれていない部分をコメントさせていただきましたので、ご確認お願いします 🙏 
思っていたより見落としがあり、お手数おかけすることになってしまい申し訳ありません 🙇

2024-07-10 01:44 UTC, blendthink commented on test/view/main_page_layout_test.dart
> +  provideDummy<
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)
これがないと型判定が現状うまくいかないのですね、把握できていなかったので勉強になりました！
ご対応ありがとうございます 🙏 

![memo-badge](https://img.shields.io/badge/review-memo-lightgrey) 
sealed class の場合は、これがないと次のエラーが発生してしまう。
<details><summary>Details</summary>
<p>

```shell
The following MissingDummyValueError object was thrown running a test:
  MissingDummyValueError: Result<WeatherInfo, ({AppException exception, StackTrace stackTrace})>

This means Mockito was not smart enough to generate a dummy value of type
'Result<WeatherInfo, ({AppException exception, StackTrace stackTrace})>'. Please consider using
either 'provideDummy' or 'provideDummyBuilder'
functions to give Mockito a proper dummy value.

Please note that due to implementation details Mockito sometimes needs users
to provide dummy values for some types, even if they plan to explicitly stub
all the called methods.
```

</p>
</details> 

FYI:
https://pub.dev/documentation/mockito/latest/mockito/provideDummy.html

2024-07-10 01:44 UTC, blendthink commented on test/view/main_page_layout_test.dart
> +        when(mockWeatherRepository.fetchWeather()).thenAnswer((_) => response);
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg)
初期画面のテストではボタンをクリックしないため `weatherRepository.fetchWeather()` は呼び出されません。よって、この辺りの実装は不要です。削除お願いします 🙏

2024-07-10 01:44 UTC, blendthink commented on test/view/main_page_layout_test.dart
> +        expect(defaultTextFinder, findsNWidgets(2));
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)
きちんと２つ存在していることを確認されていてステキです✨

2024-07-10 01:44 UTC, blendthink commented on test/view/main_page_layout_test.dart
> +        expect(minTemperatureTextFinder, findsNWidgets(1));
![imo-badge](https://img.shields.io/badge/review-imo-skyblue.svg) 
修正しなくてもいいかもと思いつつ、少し気になったので指摘しておくと、１つのみ表示されていることを確認する場合は、他の箇所と合わせて `findsOneWidget` を使うと統一感でて良さそうです！
```suggestion
        // 最高気温の表記
        final maxTemperatureTextFinder = find.text('16 ℃');
        expect(maxTemperatureTextFinder, findsOneWidget);

        // 最低気温の表記
        final minTemperatureTextFinder = find.text('7 ℃');
        expect(minTemperatureTextFinder, findsOneWidget);
```

2024-07-10 01:44 UTC, blendthink commented on test/view/main_page_layout_test.dart
> +    group('異常形', () {
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg) 
typo のようです。
```suggestion
    group('異常系', () {
```

2024-07-10 01:44 UTC, blendthink commented on test/view/main_page_layout_test.dart
> +      testWidgets('APIから取得した天候データを画像として表示', (tester) async {
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
`testWidgets` 内で `for` 文を記載して複数のテストを行っていますが、 `setUp` や `tearDown` で設定したものがはじめの１回しか呼び出されないため、思いもよらない挙動になってしまいかねません。
そのため `for` 文の中で `testWidgets` や `_setUpScreen` を呼び出すように修正お願いします 🙏 

参考としてコード記載しておきます。

<details><summary>Details</summary>
<p>

```dart
group('APIから取得した天候データを画像として表示', () {
  final assets = [
    (WeatherCondition.cloudy, Assets.images.cloudy.svg()),
    (WeatherCondition.sunny, Assets.images.sunny.svg()),
    (WeatherCondition.rainy, Assets.images.rainy.svg()),
  ];

  for (final (weatherCondition, svg) in assets) {
    testWidgets('$weatherCondition のときは $svg が表示される', (tester) async {
      _setUpScreen(tester);
      final successObject = Success<WeatherInfo, _FailureValue>(
        WeatherInfo(
          weatherCondition: weatherCondition,
          maxTemperature: 16,
          minTemperature: 7,
          date: DateTime.parse('2020-04-01T12:00:00+09:00'),
        ),
      );
      final response = Future<Success<WeatherInfo, _FailureValue>>.value(
        successObject,
      );

      when(mockWeatherRepository.fetchWeather())
          .thenAnswer((_) => response);

      await tester.pumpWidget(
        ProviderScope(
          overrides: [
            weatherRepositoryProvider
                .overrideWithValue(mockWeatherRepository),
          ],
          child: const MaterialApp(
            home: Scaffold(
              body: MainPageLayout(),
            ),
          ),
        ),
      );

      // `Reload` ボタンを押した際の挙動
      final reloadTextFinder = find.text('Reload');
      await tester.tap(reloadTextFinder);
      await tester.pumpAndSettle();

      // 画像の表示
      final svgPicFinder = find.svg(svg.bytesLoader);
      expect(svgPicFinder, findsOneWidget);
    });
  }
});
```

</p>
</details>

2024-07-10 07:31 UTC, tom1236908745 commented on test/view/main_page_layout_test.dart
> +  });
[fix: setUp → tearDown](https://github.com/tom1236908745/flutter-training-weather-app/pull/24/commits/5d34a20f72e8a4750590e225a21b7c6be94ba219)

上記コミットで対応させて頂きました！

2024-07-10 07:32 UTC, tom1236908745 commented on test/view/main_page_layout_test.dart
> +import 'package:flutter_training/model/weather_info.dart' as model;
[fix: import 文 の接頭辞を削除](https://github.com/tom1236908745/flutter-training-weather-app/pull/24/commits/8d3f8358377cb18cec947b508aea5c3a3853f7c2)

以前同じクラス名のものを、インポートしていたのですが、
現状不要でしたので、削除させて頂きました。

2024-07-10 07:33 UTC, tom1236908745 commented on test/view/main_page_layout_test.dart
> +          })>>(commonSuccessObject);
[feat: 共通の型 _FailureValue を使用](https://github.com/tom1236908745/flutter-training-weather-app/pull/24/commits/17be342164aeae39cc501d4b7fedecdc55698883)

上記コミットで対応させて頂きました

2024-07-10 07:33 UTC, tom1236908745 commented on test/view/main_page_layout_test.dart
> +          })>>(commonSuccessObject);
[fix: 不要な実装の削除](https://github.com/tom1236908745/flutter-training-weather-app/pull/24/commits/3850c24608eabd74245b66ca892b2a5a1cd0e461)

上記コミットで対応させて頂きました！

2024-07-10 07:33 UTC, tom1236908745 commented on test/view/main_page_layout_test.dart
> +        when(mockWeatherRepository.fetchWeather()).thenAnswer((_) => response);
[fix: 不要な実装の削除](https://github.com/tom1236908745/flutter-training-weather-app/pull/24/commits/3850c24608eabd74245b66ca892b2a5a1cd0e461)

上記コミットで対応させて頂きました！

2024-07-10 07:34 UTC, tom1236908745 commented on test/view/main_page_layout_test.dart
> +        expect(minTemperatureTextFinder, findsNWidgets(1));
[fix: finderの変更 findsNWidgets(1) → findsOneWidget](https://github.com/tom1236908745/flutter-training-weather-app/pull/24/commits/959f7c25ef5d81962c1f1846cb53b2aa0e0e6f5e)

上記コミットで対応させて頂きました！

2024-07-10 07:34 UTC, tom1236908745 commented on test/view/main_page_layout_test.dart
> +      testWidgets('APIから取得した天候データを画像として表示', (tester) async {
[fix: testWidget の記述場所を変更](https://github.com/tom1236908745/flutter-training-weather-app/pull/24/commits/2f0d98d87d822f2699cecdd4790e85d64d3ab03f)

上記コミットで対応させて頂きました！

2024-07-10 08:16 UTC, blendthink approved these changes
@tom1236908745 
もろもろレビュー漏れていた箇所のご対応ありがとうございました 🙏 
LGTM です 🎉 
![LGTM](https://image.lgtmoon.dev/255253)

2024-07-10 10:24 UTC, merged